<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS5xernB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS5xernB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS5xernB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS5xernB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS5xernB\App_KernelDevDebugContainer([
    'container.build_hash' => 'S5xernB',
    'container.build_id' => '56465b07',
    'container.build_time' => 1673429590,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS5xernB');
