<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXRKO9kj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXRKO9kj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXRKO9kj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXRKO9kj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXRKO9kj\App_KernelDevDebugContainer([
    'container.build_hash' => 'XRKO9kj',
    'container.build_id' => 'd136a535',
    'container.build_time' => 1673347010,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXRKO9kj');
