<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJg5A97j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJg5A97j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJg5A97j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJg5A97j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJg5A97j\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jg5A97j',
    'container.build_id' => 'a533cb16',
    'container.build_time' => 1673347026,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJg5A97j');
